# Generated by Django 3.1.7 on 2021-08-13 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_cardealer_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardealer',
            name='state',
        ),
    ]
