# Generated by Django 3.1.7 on 2021-08-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_cardealer_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardealer',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
