# Generated by Django 3.1.7 on 2021-08-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_car_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='zipcode',
        ),
    ]
